name: Autograding Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Test for Problem 1
      run: python -m unittest tests/test_problem1.py

    - name: Run Test for Problem 2
      run: python -m unittest tests/test_problem2.py

    - name: Run Test for Problem 3
      run: python -m unittest tests/test_problem3.py
